server:
  port: 8080

spring:
  profiles:
    active: true

#database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meet?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
            use_sql_comments: true
            default_schema: meet

